version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - referral_network
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=4000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - referral_network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_API_BASE_URL=https://referrals.bank-juno.com
    volumes:
      - ./frontend/admin:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - referral_network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - referral_network

volumes:
  mongodb_data:

networks:
  referral_network:
