version: '3.8'

services:
  mongodb:
    image: mongo:latest  
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  
    networks:
      - referral_network
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]  # Enable replica set

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "80:4000"  # Expose backend on host port 80
    environment:
      - PORT=4000
      - CLIENT_URL=http://localhost:3000  # For local frontend development
    volumes:
      - ./backend:/app  
      - /app/node_modules  # Prevent host node_modules from overwriting container's node_modules
    networks:
      - referral_network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"  # Map container's port 3000 to host's port 3000
    environment:
      - REACT_APP_API_BASE_URL=http://backend:4000  # Backend API URL
    volumes:
      - ./frontend/admin:/usr/src/app  # Mount the source code for live development
      - /usr/src/app/node_modules      # Prevent overwriting container's node_modules
    networks:
      - referral_network
    depends_on:
      - backend

volumes:
  mongodb_data:

networks:
  referral_network:
