services:
  percona:
    image: percona/percona-server-mongodb:latest
    container_name: percona
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - referral_network
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=referral_db  # Set the default database if needed
    # This ensures that MongoDB starts with authentication enabled

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=4000
      - CLIENT_URL=http://localhost:3000
      - DB_URI=mongodb://admin:adminpassword@percona:27017/referral_db?replicaSet=rs0
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - referral_network
    depends_on:
      - percona

  frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_API_BASE_URL=https://referrals.bank-juno.com
    volumes:
      - ./frontend/admin:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - referral_network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - referral_network

volumes:
  mongodb_data:

networks:
  referral_network:
