services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Expose the app on port 8080 on the host, and 80 on the container
    environment:
      - NODE_ENV=production  # Make sure we're in production mode
    restart: unless-stopped